CREATE DATABASE host_monitoring;

CREATE TABLE host_list (
	`name` VARCHAR(64) NOT NULL PRIMARY KEY,
	`ip` VARCHAR(64) NOT NULL UNIQUE,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB CHARSET=UTF8MB4;

CREATE TABLE host_status (
	`name` VARCHAR(64) NOT NULL PRIMARY KEY,
	`alive` BOOLEAN, 
	`lastAliveTime` TIMESTAMP NULL DEFAULT NULL
) ENGINE=INNODB CHARSET=UTF8MB4;


DROP TABLE host_list;

DROP TABLE host_status;

INSERT INTO `host_list` (`name`, `ip`, `createdAt`, `updatedAt`)
VALUE ('bbbnn', '19n', NOW(), NOW());